link_libraries(2DGraphics1)
add_subdirectory(NimotsuKunAlphaBlend)
add_subdirectory(NimotsuKunAlphaTest)
add_subdirectory(NimotsuKunImage)
add_subdirectory(displayImage)
add_subdirectory(displayImageAdditionalBlend)
add_subdirectory(displayImageAlphaBlend)
add_subdirectory(displayImageAlphaTest)
add_subdirectory(displayImagePartially)