add_subdirectory(GameLibs)

add_subdirectory(01_FirstGame)
add_subdirectory(02_2DGraphics1)
add_subdirectory(03_2DGraphics2)
add_subdirectory(04_RealTime)
add_subdirectory(05_Sequence1)
add_subdirectory(06_Font1)
add_subdirectory(07_2DActionGame)
add_subdirectory(08_2DCollision)
add_subdirectory(09_InputDevices)
add_subdirectory(10_Sequence2)
